feat: add stc support
OneKeyHQ/onekey-firmware pull request #5
Opened 2021-09-18 08:24 UTC by dydysy

主要增加 获取地址，签名交易，签名消息，验证消息签名。

- StarcoinGetAddress
- StarcoinSignTx
- StarcoinSignMessage
- StarcoinVerifyMessage

todo: 消息验证签名，会通过publikey 生成 地址。 然而生成地址不能匹配。 但不影响验证功能。

2021-09-22 02:32 UTC, danielsocials requested changes

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/fsm.h
> -
这种改动看起来没有必要，新加代码跟在后面就好，这样diff看起来清晰一些

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/fsm_msg_starcoin.h
> +    char address[MAX_STARCOIN_ADDRESS_SIZE];
最好初始化局部变量address， address[MAX_STARCOIN_ADDRESS_SIZE]={0};

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/protob/Makefile
> +SKIPPED_MESSAGES += Ethereum Lisk NEM Solana Starcoin Stellar
同上，Starcoin放最后

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/starcoin.c
> +    return 0;
0->NULL

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/starcoin.c
> +    return 0;
0->NULL

2021-09-22 02:32 UTC, danielsocials commented on legacy/firmware/starcoin.c
> +      split_message((const uint8_t *)address, strlen(address), 16);
@lihuanhuan @vxtarget  这两个layout函数是不是有通用的？

2021-09-22 02:32 UTC, danielsocials commented on python/src/trezorlib/cli/starcoin.py
> +# GNU Lesser General Public License for more details.
新加文件的license 换成我们的

2021-09-22 02:32 UTC, danielsocials commented on python/src/trezorlib/starcoin.py
> +# This library is distributed in the hope that it will be useful,
Lic同上

2021-09-22 02:32 UTC, danielsocials commented on tools/build_protobuf
> -    $PROTOB/messages-solana.proto \
不需要改solana的位置

2021-09-22 02:43 UTC, dydysy commented on tools/build_protobuf
> -    $PROTOB/messages-solana.proto \
本意是想按照文件名升序排列。  因为我观察源文件是有意的按照 文件名排列的。

这里我们不需要这样做吗？

2021-09-22 03:08 UTC, dydysy commented on legacy/firmware/fsm_msg_starcoin.h
> +    char address[MAX_STARCOIN_ADDRESS_SIZE];
确实应该初先始化一下再使用。

2021-09-22 03:41 UTC, liyanhrxy commented
@dydysy STC生成地址时使用hash函数了吗？如果是的话，获取地址时最好把，公钥带上

2021-09-22 03:45 UTC, dydysy commented
> @dydysy STC生成地址时使用hash函数了吗？如果是的话，获取地址时最好把公钥带上

使用了。 那我现在就直接加上算了， 之前考虑过这个问题。  本来准备等插件那边主动提这个问题，再加的。

2021-09-22 08:54 UTC, liyanhrxy commented on legacy/firmware/starcoin.c
> +const HDNode *starcoin_deriveNode(const uint32_t *address_n,
这个方法其实没必要吧，用下面这个现成的方法就好感觉
```
HDNode *node = fsm_getDerivedNode(ED25519_NAME, msg->address_n,
                                    msg->address_n_count, NULL);
```

2021-09-22 10:13 UTC, dydysy commented on legacy/firmware/starcoin.c
> +const HDNode *starcoin_deriveNode(const uint32_t *address_n,
从运行结果来看不能这样。 现在不会打日志，有点难说出原因。
我会再试一次。

2021-09-22 10:21 UTC, liyanhrxy commented on legacy/firmware/starcoin.c
> +const HDNode *starcoin_deriveNode(const uint32_t *address_n,
？？，solana我就是这么用的呀，没啥问题

2021-09-22 10:46 UTC, dydysy commented on legacy/firmware/starcoin.c
> +const HDNode *starcoin_deriveNode(const uint32_t *address_n,
hdnode_fill_public_key(node);
对比了下， 应该是我少了这一步，应该是可以直接用 fsm_getDerivedNode

2021-09-23 03:01 UTC, vxtarget approved these changes

2021-09-23 08:23 UTC, danielsocials commented on legacy/firmware/starcoin.c
> +  memcpy(buf + 32, msg->raw_tx.bytes, msg->raw_tx.size);
需要检查下msg->raw_tx.size， 防止溢出

2021-09-23 08:27 UTC, dydysy commented on legacy/firmware/starcoin.c
> +  memcpy(buf + 32, msg->raw_tx.bytes, msg->raw_tx.size);
数据进来的时候，我理解的是做了一层 maxsize 限制。StarcoinSignTx_size 应该是够用的。

补充一下，没有坏处。 我加上。

2021-09-23 08:43 UTC, dydysy commented on legacy/firmware/starcoin.c
> +  memcpy(buf + 32, msg->raw_tx.bytes, msg->raw_tx.size);
顺带测试了下，超出提前定义好的 maxsize ，  消息层就拦截劝返了 Error: DataError: bytes overflow 。

2021-09-23 08:58 UTC, danielsocials commented on legacy/firmware/starcoin.c
> +  memcpy(buf + 32, msg->raw_tx.bytes, msg->raw_tx.size);
对，我看成MAX_STARCOIN_ADDRESS_SIZE了，那可以不改

2021-09-23 08:59 UTC, danielsocials approved these changes

2021-09-24 02:05 UTC, merged